### ISSUE TITLE
Error: mw7TkYgsUoGz1j7nm2vcQ5sefCXWWtMznu has no matching Script

### ISSUE THREAD

**Issue by Yangk030208** [bitcoinjs/bitcoinjs-lib#1101]
I tried to create the transaction, but this error occurred. The full information is at the bottom. why?thank you .
`
Error: mw7TkYgsUoGz1j7nm2vcQ5sefCXWWtMznu has no matching Script
    at Object.toOutputScript (/home/thing/xishi/grow_sign/node_modules/bitcoinjs-lib/src/address.js:87:9)
    at TransactionBuilder.addOutput (/home/thing/xishi/grow_sign/node_modules/bitcoinjs-lib/src/transaction_builder.js:609:29)
    at outputs.forEach.output (/home/thing/xishi/grow_sign/lib/middleware/btc_helper.js:128:11)
    at Array.forEach (<anonymous>)
    at Object.BTCHelper.sendBtc (/home/thing/xishi/grow_sign/lib/middleware/btc_helper.js:123:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by Yangk030208** [comment]
There are other errors in my code. I'm sorry,

**Comment by dcousens** [comment]
@Yangk030208 care to share what the problem was for others?
