### ISSUE TITLE
npm install error under bitcoinjs-lib folder

### ISSUE THREAD

**Issue by JQiMeng** [bitcoinjs/bitcoinjs-lib#1124]
```
> tiny-secp256k1@0.1.0 install D:\****\js\bitcoinjs-lib\node_modules\bip32\node_modules\tiny-secp256k1
> node-gyp rebuild


D:\****\js\bitcoinjs-lib\node_modules\bip32\node_modules\tiny-secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

D:\****\js\bitcoinjs-lib\node_modules\bip32\node_modules\tiny-secp256k1\build\secp256k1.vcxproj(20,3): error MSB4019: can't import  D:\Microsoft.Cpp.Default.
props
 <Import> path error or file don't exist
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\****\js\bitcoinjs-lib\node_modules\bip32\node_modules\tiny-secp256k1
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiny-secp256k1@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
npm install error under bitcoinjs-lib folder，is this normal or how to fix it .
thanks

**Comment by fanatid** [comment]
https://github.com/cryptocoinjs/secp256k1-node#windows should work for `tiny-secp256k1` too.

**Comment by dcousens** [comment]
@fanatid linked to `secp256k1-node` instructions over at [`tiny-secp256k1`](https://github.com/bitcoinjs/tiny-secp256k1/blob/498d8d24eab67953b1321846ae724b4f36e9b605/README.md#installation)
