### ISSUE TITLE
ERROR: Unexpected token: name (createHash)

### ISSUE THREAD

**Issue by davidapple** [bitcoinjs/bitcoinjs-lib#1221]
When running `browserify -r bitcoinjs-lib -s bitcoin | uglifyjs > bitcoinjs.min.js`

I get the following error:

```
Parse error at 0:245,4
let createHash = require('create-hash')
    ^
ERROR: Unexpected token: name (createHash)
    at JS_Parse_Error.get (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
    at fatal (/usr/local/lib/node_modules/uglify-js/bin/uglifyjs:291:53)
    at run (/usr/local/lib/node_modules/uglify-js/bin/uglifyjs:235:9)
    at Socket.<anonymous> (/usr/local/lib/node_modules/uglify-js/bin/uglifyjs:168:9)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by dabura667** [comment]
What are the outputs to the following 3 commands?
```
node -v
npm -v
browserify --version
```

**Comment by davidapple** [comment]
```
node v9.2.0
npm v5.5.1
browserify v16.2.2
```

**Comment by dcousens** [comment]
@davidapple that isn't browserify issue.
That is an `uglifyjs` issue (read your stack trace).

10 seconds looking at the [uglifyjs documentation](https://www.npmjs.com/package/uglify-js) showed me:

> uglify-js only supports JavaScript (ECMAScript 5).

Please read the documentation of what you are using.

**Comment by junderw** [comment]
@davidapple Uninstall `uglifyjs` and install `uglify-es` (The command stays the same)

https://www.npmjs.com/package/uglify-es
