### ISSUE TITLE
What's the proper and latest way to generate child public keys out of an extended pub key?

### ISSUE THREAD

**Issue by ceX2MsjvD8Rs7uac** [bitcoinjs/bitcoinjs-lib#1238]
I tried out some snippets to do this, but none of them work, some of them use HDNode which is undefined when i test it...

Why does my key start out with zpub and not with xpub?
`zpub6nYqvTejCbqMTRTGz9rHkJnrJKbLsx36LqLnUJChDdJ6a5NA7hBumEpn9HTSDgWpNTNCponkPCBL5VKeAaScVxbXa1H4RPmA4j19rzgJPRp`

**Comment by jackyzq** [comment]
Took a look at the code, seems like this is the way to do it, if we don't have access to the HDnode module anymore.
```
var addressIndex = 0;
var node = bitcoin.bip32.fromBase58(xpub, bitcoin.networks.testnet);
var address = bitcoin.payments.p2pkh({ pubkey: node.derive(addressIndex).publicKey, network: bitcoin.networks.testnet}).address
```

**Comment by ceX2MsjvD8Rs7uac** [comment]
> 
> 
> Took a look at the code, seems like this is the way to do it, if we don't have access to the HDnode module anymore.
> 
> ```
> var addressIndex = 0;
> var node = bitcoin.bip32.fromBase58(xpub, bitcoin.networks.testnet);
> var address = bitcoin.payments.p2pkh({ pubkey: node.derive(addressIndex).publicKey, network: bitcoin.networks.testnet}).address
> ```
    version !== network.bip32.public) throw new TypeError('Invalid network version')
                                      ^

TypeError: Invalid network version
    at Object.fromBase58 (C:\Users\Attractor\Desktop\payment\node_modules\bip32\index.js:220
:45)
    at Object.<anonymous> (C:\Users\Attractor\Desktop\payment\main.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)

**Comment by ceX2MsjvD8Rs7uac** [comment]
> `C:\Users\Home\Desktop\payment\node_modules\bip32\index.js:219
  if (version !== network.bip32.private &&
                                ^

TypeError: Cannot read property 'private' of undefined
    at Object.fromBase58 (C:\Users\Home\Desktop\payment\node_modules\bip32\index.js:219
:33)
    at Object.<anonymous> (C:\Users\Home\Desktop\payment\main.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
`

**Comment by jackyzq** [comment]
It would help if you showed your code where your error occurred. From your previous code it looks like your master public key is using the live network. So you'll have to change the network in the code to bitcoin.network.bitcoin

**Comment by ceX2MsjvD8Rs7uac** [comment]
> .

tried that too =/ 
got a different error saying bip32.private = undefined...

I'm doing this now:

`
let bitcoin = require('bitcoinjs-lib');
const assert = require('assert');
const bip32 = require('bip32');

function getAddress (node, network) {
  return bitcoin.payments.p2pkh({ pubkey: node.publicKey, network }).address
}

const path = "m/0'/0/0"
const root = bip32.fromSeed(Buffer.from('dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd', 'hex'))
const child1 = root.derivePath(path)

//assert.equal(getAddress(child1), '1JHyB1oPXufr4FXkfitsjgNB5yRY9jAaa7');
console.log(getAddress(child1));

`

Now I need to find out where to put the xpub :+1:

**Comment by ceX2MsjvD8Rs7uac** [comment]
version !== network.bip32.public) throw new TypeError('Invalid network version')
                                      ^

TypeError: Invalid network version
    at Object.fromBase58 (C:\Users\Attractor\Desktop\payment\node_modules\bip32\index.js:220
:45)
    at Object.<anonymous> (C:\Users\Attractor\Desktop\payment\main.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)

**Comment by jackyzq** [comment]
It's probably your master public key's version.
Check out this issue.
https://github.com/bitcoinjs/bitcoinjs-lib/issues/966

**Comment by ceX2MsjvD8Rs7uac** [comment]
> 
> 
> It's probably your master public key's version.
> Check out this issue.
> #966

says nothing about zpub... i generated mine using electrum..

**Comment by ceX2MsjvD8Rs7uac** [comment]
Getting the same error with a confirmed xpub address too: 
``` 
  if (version !== network.bip32.private &&
                                ^

TypeError: Cannot read property 'private' of undefined
    at Object.fromBase58 (C:\Users\Attractor\Desktop\payment\node_modules\bip32\index.js:219
:33)
    at Object.<anonymous> (C:\Users\Attractor\Desktop\payment\main.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)```

**Comment by jackyzq** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/issues/966#issuecomment-356320324

Please read carefully. There is an exact comment talking about electrum generated zpub addresses.

**Comment by ceX2MsjvD8Rs7uac** [comment]
> 
> 
> [#966 (comment)](https://github.com/bitcoinjs/bitcoinjs-lib/issues/966#issuecomment-356320324)
> 
> Please read carefully. There is an exact comment talking about electrum generated zpub addresses.
=) oh

**Comment by ceX2MsjvD8Rs7uac** [comment]
const b58 = require('bs58check');
Do I really need this? Is this not built into bitcoinjs-lib already?

**Comment by ceX2MsjvD8Rs7uac** [comment]
I really don't know where the payments will go if I send coins to that generated address..
The addresses shown in electrum are totally different and there is no address showing the balance of my xpub/zpub.

**Comment by LeeKorbisCa** [comment]
Why can't this be supported within bitcoinjs-lib itself? :s

**Comment by junderw** [comment]
> Why can't this be supported within bitcoinjs-lib itself? :s

Read the discussion on the Pull Request. Grab some popcorn, it's long.

https://github.com/bitcoinjs/bitcoinjs-lib/pull/927

Extra context: ecdsa (the creator of Electrum) showed up and said he would write a BIP but no such BIP ever appeared.

Without a BIP, who's to say Electrum doesn't change zpub to Qpub tomorrow? Then what? Do we just support any random string with "pub" in it? What if that changes? etc.

Electrum has used zpubs for many years and I doubt they'll change it... but since it's not a standard and it's just "whatever electrum decides to do" it makes it difficult to officially support it as a library.
