### ISSUE TITLE
ECPair.makeRandom is not function 

### ISSUE THREAD

**Issue by Mattie777** [bitcoinjs/bitcoinjs-lib#1269]
Hello 
this is my script 
var bitcoin = ("bitcoinjs-lib");
var keyPair = bitcoin.ECPair.makeRandom();
console.log(keyPair.toWIF());

TypeError: Cannot read property 'makeRandom' of undefined
    at Object.<anonymous> (C:\Users\Desktop\bitcoin\myrules.js:2:30)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

No idea what is happening. This is my first try so help me guy to understand this,  and what i need to fix in this .

**Comment by dabura667** [comment]
`var bitcoin = ("bitcoinjs-lib");`

vvvvvvvvvvvvvvvvvvvvvvv

`var bitcoin = require("bitcoinjs-lib");`

**Comment by dabura667** [comment]
It happens to all of us at least once. Let us know if you have any other questions.

**Comment by GOmunkul** [comment]
> var keyPair = bitcoin.ECPair.makeRandom();
Uncaught TypeError: Cannot read properties of undefined (reading 'makeRandom')
node.js - v16.14.0
What am I doing wrong?

**Comment by junderw** [comment]
bitcoinjs-lib v6 removed ECPair.

It's recommended to use the `bip32` package if possible, since HD keys are the norm now... but the `ecpair` package exists on npm. Please read the documentation (README, CHANGELOG, etc etc) before asking any questions.

**Comment by JamesCodes0** [comment]
> bitcoinjs-lib v6 removed ECPair.

> const keyPair = ECPair.makeRandom()
> Uncaught ReferenceError: ECPair is not defined

So how do you get this to work?

**Comment by junderw** [comment]
https://github.com/bitcoinjs/ecpair/blob/v2.0.1/README.md#example
