### ISSUE TITLE
 Cannot find module 'tiny-secp256k1'

### ISSUE THREAD

**Issue by asas54** [bitcoinjs/bitcoinjs-lib#1272]
what is this? Why is there a problem, where is the lack of tiny-secp256k1?

**Comment by ish3lan** [comment]
I get this error also:

`> tiny-secp256k1@1.0.1 install /Users/xxx/Udacity/Block Chain/Project 4/node_modules/tiny-secp256k1
> node-gyp rebuild

2018-12-04 21:45:30.232 xcodebuild[32838:10981264] [MT] PluginLoading: Required plug-in compatibility UUID D7881182-AD00-4C36-A94D-F45FC9B0CF85 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-12-04 21:45:30.233 xcodebuild[32838:10981264] [MT] PluginLoading: Required plug-in compatibility UUID D7881182-AD00-4C36-A94D-F45FC9B0CF85 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-12-04 21:45:30.234 xcodebuild[32838:10981264] [MT] PluginLoading: Required plug-in compatibility UUID D7881182-AD00-4C36-A94D-F45FC9B0CF85 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-12-04 21:45:30.235 xcodebuild[32838:10981264] [MT] PluginLoading: Required plug-in compatibility UUID D7881182-AD00-4C36-A94D-F45FC9B0CF85 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AutoIndentWithSave.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-12-04 21:45:30.236 xcodebuild[32838:10981264] [MT] PluginLoading: Required plug-in compatibility UUID D7881182-AD00-4C36-A94D-F45FC9B0CF85 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AtAutoCompletion.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-12-04 21:45:30.237 xcodebuild[32838:10981264] [MT] PluginLoading: Required plug-in compatibility UUID D7881182-AD00-4C36-A94D-F45FC9B0CF85 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-12-04 21:45:30.238 xcodebuild[32838:10981264] [MT] PluginLoading: Required plug-in compatibility UUID D7881182-AD00-4C36-A94D-F45FC9B0CF85 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ActivatePowerMode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/secp256k1/native/addon.o
../native/addon.cpp:239:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        secp256k1_ec_privkey_negate(context, tweak_negated); // returns 1 always
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:79:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:141:21: note: in instantiation of function template specialization '(anonymous namespace)::assumeCompression<2, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested
      here
        const auto flags = assumeCompression<2>(info, pA);
                           ^
../native/addon.cpp:79:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:173:21: note: in instantiation of function template specialization '(anonymous namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested
      here
        const auto flags = assumeCompression<1>(info, p);
                           ^
../native/addon.cpp:86:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:188:21: note: in instantiation of function template specialization '(anonymous namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value> >' requested here
        const auto flags = assumeCompression<1>(info);
                           ^
../native/addon.cpp:20:32: warning: unused variable 'ZERO' [-Wunused-const-variable]
        const std::array<uint8_t, 32> ZERO = {};
                                      ^
5 warnings generated.
  CC(target) Release/obj.target/secp256k1/native/secp256k1/src/secp256k1.o
In file included from ../native/secp256k1/src/secp256k1.c:13:
../native/secp256k1/src/group_impl.h:686:12: warning: unused function 'secp256k1_gej_has_quad_y_var' [-Wunused-function]
static int secp256k1_gej_has_quad_y_var(const secp256k1_gej *a) {
           ^
../native/secp256k1/src/group_impl.h:113:13: warning: unused function 'secp256k1_ge_set_gej_var' [-Wunused-function]
static void secp256k1_ge_set_gej_var(secp256k1_ge *r, secp256k1_gej *a) {
            ^
../native/secp256k1/src/group_impl.h:267:12: warning: unused function 'secp256k1_gej_is_valid_var' [-Wunused-function]
static int secp256k1_gej_is_valid_var(const secp256k1_gej *a) {
           ^
In file included from ../native/secp256k1/src/secp256k1.c:15:
../native/secp256k1/src/ecmult_const_impl.h:123:13: warning: unused function 'secp256k1_ecmult_const' [-Wunused-function]
static void secp256k1_ecmult_const(secp256k1_gej *r, const secp256k1_ge *a, const secp256k1_scalar *scalar) {
            ^
4 warnings generated.
  SOLINK_MODULE(target) Release/secp256k1.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/secp256k1.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxx/Udacity/Block Chain/Project 4/node_modules/tiny-secp256k1
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN project-4@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by junderw** [comment]
@ish3lan your issue is unrelated. your mac does not have the proper node build environment for cpp addons.

**Comment by junderw** [comment]
Let me know if the issue persists.
