### ISSUE TITLE
How to create a transaction without this previous input hash 

### ISSUE THREAD

**Issue by sukeerthi117** [bitcoinjs/bitcoinjs-lib#1338]
how can i send the previous transactionid as this is my first transaction,

**i am trying like this
  txb.addInput("", 0)** 

but it is giving error

/home/ahex/Desktop/tokenize.node/node_modules/typeforce/extra.js:19
    throw ERRORS.tfCustomError(name + '(Length: ' + length + ')', name + '(Length: ' + value.length + ')')
    ^
Error: Expected Buffer(Length: 32), got Buffer(Length: 0)
    at Object.tfCustomError (/home/ahex/Desktop/tokenize.node/node_modules/typeforce/errors.js:80:10)
    at Length (/home/ahex/Desktop/tokenize.node/node_modules/typeforce/extra.js:19:18)
    at typeforce (/home/ahex/Desktop/tokenize.node/node_modules/typeforce/index.js:233:9)
    at Function.Transaction.isCoinbaseHash (/home/ahex/Desktop/tokenize.node/node_modules/bitcoinjs-lib/src/transaction.js:145:3)
    at TransactionBuilder.__addInputUnsafe (/home/ahex/Desktop/tokenize.node/node_modules/bitcoinjs-lib/src/transaction_builder.js:558:19)
    at TransactionBuilder.addInput (/home/ahex/Desktop/tokenize.node/node_modules/bitcoinjs-lib/src/transaction_builder.js:550:15)
    at send (/home/ahex/Desktop/tokenize.node/controllers/register-controller.js:187:7)
    at Object.<anonymous> (/home/ahex/Desktop/tokenize.node/controllers/register-controller.js:193:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)

**Comment by junderw** [comment]
Are you trying to create a coinbase transaction for the mining reward?

TransactionBuilder does not support mining reward transactions, and can only create transactions with a valid UTXO to spend.

**Comment by sukeerthi117** [comment]
i am new to crypto ,

till now i didnt create any transaction  so i dont have tranasctionid ...how can i send previous txid for input

**Comment by sukeerthi117** [comment]
Actually, i am new to crypto technology

 i want to create hd wallets (bitcoin,litecoin,bitcoincash,dash) for my exchange application ..i am able to create wallet address using bit39 now i am trying to create transaction ..

before going to implement i want to know that is transactionbuilder is suitable for hdwallet or is there any other ways  to create a transaction for hd wallet addresses

**Comment by junderw** [comment]
Yes. Bitcoinjs-lib is suitable for an exchange wallet. Many exchanges and wallet providers (Bitgo etc.) use it.

Please read the unit tests and integration tests to see examples of how to use this library.

Also, look into BIP39, BIP32, and start thinking of path logic for your exchange (BIP44 and BIP45 show some path logic examples for normal people, but an exchange has different requirements, so I don't recommend BIP44 etc. for an exchange.)
