### ISSUE TITLE
sighashTypes.indexOf is not a function error when trying to sign transactions.

### ISSUE THREAD

**Issue by EmmanuelAmodu** [bitcoinjs/bitcoinjs-lib#1774]
I get this error every time I try to sign a transaction.

```
(node:19) UnhandledPromiseRejectionWarning: TypeError: sighashTypes.indexOf is not a function
    at getHashForSig (/app/node_modules/bitcoinjs-lib/src/psbt.js:937:36)
    at getHashAndSighashType (/app/node_modules/bitcoinjs-lib/src/psbt.js:920:41)
    at Psbt.signInput (/app/node_modules/bitcoinjs-lib/src/psbt.js:522:35)
    at Handshake.<anonymous> (/app/main.js:119:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Here is the code.
```
        psbt.addInput({
          hash: utxosRaw[j].tx_hash_big_endian,
          index: j,
          witnessUtxo: {
            script: Buffer.from(scriptPubKey, 'hex'),
            value: parseFloat(utxoTransaction.vout[0].value) * 100000000
          },
          redeemScript: redeemScript,
        })
       psbt.signInput(j, ecpair, bitcoin.networks.bitcoin);
```

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/v6.0.1/ts_src/psbt.ts#L630-L634

See the arguments.

```diff
- psbt.signInput(j, ecpair, bitcoin.networks.bitcoin);
+ psbt.signInput(j, ecpair); 
```

**Comment by junderw** [comment]
Also, `index: j` is incorrect.

index for the input is normally called `vout` in most APIs.

It refers to the index of the output in the transaction pointed to by `hash`.
