### ISSUE TITLE
Non-witness UTXO hash for input doesn't match the hash specified in the prevout

### ISSUE THREAD

**Issue by claretnnamocha** [bitcoinjs/bitcoinjs-lib#1778]
Hi,  I'm trying to sign a transaction using the library but I'm getting below error:

`Error: Non-witness UTXO hash for input #0 doesn't match the hash specified in the prevout`

Could someone please help me understand where am I going wrong?

Below is my code:

```typescript 
import * as bitcoin from "bitcoinjs-lib";
import ECPairFactory from "ecpair";
import * as ecc from "tiny-secp256k1";

const ECPair = ECPairFactory(ecc);
const network = bitcoin.networks.testnet;

const keyPair = ECPair.fromWIF(
  "cUKap2o9EdDncymX6hehDeoQpCKt34dyPT7QtiUkcjJRs4s2Mmvz",
  network
);

//   sender address: 'mvEetKvLyhYKr9ddDEfENwZF6CwPST7gRb'
const { address: sender } = bitcoin.payments.p2pkh({
  pubkey: keyPair.publicKey,
  network,
});

// reciever address
const address = "mfs8TLBd62Pusu9dsjCugFGkop7qveLASn";

const hash = Buffer.from(
  "a9cab9b6afdafb54448d18ffe8139d15680a0fc9df8f763ad2359e4dcd8b5542",
  "hex"
);

const index = 0;

// Gotten from: https://blockstream.info/testnet/api/tx/a9cab9b6afdafb54448d18ffe8139d15680a0fc9df8f763ad2359e4dcd8b5542/hex
const nonWitnessUtxo = Buffer.from(
  "020000000001013706206e3f9386d49b4bee13595de6dd6a377a42fa0605c1cdcf65218dad9cfe0100000000feffffff0210270000000000001976a914a174b2f150d22081845a656a8db960169c6488a388acb3ec9c6a0800000016001417ae66bf433c7d51d3c8f64c327df0646cb8070a02473044022050e4ff3eca85fc783abfc20ddf17fe47ee35332a61d758b00949889ff5c0f78102206f7231fcfadfc0c39f46cc83b155da7bc389911e2d4a56b2d52deb05519f76f8012103d83a560a00549aab8bda99d33822aafae89e2980144efc27480d1fdf8aaa2c35b4092100",
  "hex"
);

const psbt = new bitcoin.Psbt({ network });
psbt.addInput({
  hash,
  index,
  nonWitnessUtxo,
});

//   send 0.001 btc
psbt.addOutput({ address, value: 100000 });

//   return balance of 0.00415410 to sender
psbt.addOutput({ address: sender, value: 415410 });

psbt.signInput(0, keyPair);

```

Error dump:

```
.../node_modules/bitcoinjs-lib/src/psbt.js:956
      throw new Error(
            ^
Error: Non-witness UTXO hash for input #0 doesn't match the hash specified in the prevout
    at getHashForSig (.../node_modules/bitcoinjs-lib/src/psbt.js:956:13)
    at getHashAndSighashType (.../node_modules/bitcoinjs-lib/src/psbt.js:920:41)
    at Psbt.signInput (.../node_modules/bitcoinjs-lib/src/psbt.js:522:35)
    at Object.<anonymous> (.../createTrxn.ts:48:6)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/Users/claretnnamocha/.config/yarn/global/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/claretnnamocha/.config/yarn/global/node_modules/ts-node/src/index.ts:1368:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

**Comment by junderw** [comment]
pass hash as a hex string. not a Buffer.
