### ISSUE TITLE
Buffer size error

### ISSUE THREAD

**Issue by jafri** [bitcoinjs/bitcoinjs-lib#1885]
Trying to create the following psbt but running into buffer error. Still learning bitcoinjs, so not entire sure what the issue is. Perhaps this is not the correct way to have two inputs and only sign one?

Code
```
    const psbt = new Psbt({ network: args.network })
        .addInput({
            hash: '2c5017ef2d2dd82c2f32f1ede31d53bccfa6ff8e4563bdeee55be565b6a30d40',
            index: 0,
            witnessUtxo: {
                script: Buffer.from('512086ed347bce97b538cbb464d1b5f3dd1ba002d09a830ca47525f454541296d89b', 'hex'),
                value: 1,
            },
            tapInternalKey: toXOnly(args.otherKeyPair!.publicKey),
        })
        .addInput({
            hash: '46f52771926fd380b2d0df67e78f80a49078b8b5ffc64c13cacce93b240ee465',
            index: 0,
            witnessUtxo: {
                script: Buffer.from('51200a91ce7b7ced003ef4a85ffb08045b695da7c66a05a3d2678353693c36ef76a1', 'hex'),
                value: 10,
            },
            tapInternalKey: toXOnly(args.keyPair.publicKey),
            sighashType: Transaction.SIGHASH_SINGLE | Transaction.SIGHASH_ANYONECANPAY,
        })
        .addOutput({
            address: 'bc1pp2guu7mua5qraa9gtlasspzmd9w603n2qk3ayeur2d5ncdh0w6ssfagcgv',
            value: 1,
        })
        .signInput(1, args.signer, [Transaction.SIGHASH_SINGLE | Transaction.SIGHASH_ANYONECANPAY])

```

Error:
```
throw new Error(`buffer size ${this.buffer.length}, offset ${this.offset}`);
          ^
Error: buffer size 125, offset 93
    at BufferWriter.end (/Users/Personal/bitcoin/node_modules/bitcoinjs-lib/src/bufferutils.js:105:11)
    at Transaction.hashForWitnessV1 (/Users/Personal/bitcoin/node_modules/bitcoinjs-lib/src/transaction.js:392:52)
    at getTaprootHashesForSig (/Users/Personal/bitcoin/node_modules/bitcoinjs-lib/src/psbt.js:1317:37)
    at Psbt.checkTaprootHashesForSig (/Users/Personal/bitcoin/node_modules/bitcoinjs-lib/src/psbt.js:836:26)
    at Psbt._signTaprootInput (/Users/Personal/bitcoin/node_modules/bitcoinjs-lib/src/psbt.js:684:31)
    at Psbt.signInput (/Users/Personal/bitcoin/node_modules/bitcoinjs-lib/src/psbt.js:632:19)
    at createSellerPbst (/Users/Personal/bitcoin/src/pbst.ts:57:10)
    at getSignedTransaction (/Users/Personal/bitcoin/src/index.ts:25:47)
    at main (/Users/Personal/bitcoin/src/index.ts:63:14)
    at Object.<anonymous> (/Users/Personal/bitcoin/src/index.ts:69:1)
```

**Comment by jafri** [comment]
Ah need two outputs for SIGHASH_SINGLE to match
