### ISSUE TITLE
Error: mandatory-script-verify-flag-failed (Public key is neither compressed or uncompressed)

### ISSUE THREAD

**Issue by vaultec81** [bitcoinjs/bitcoinjs-lib#1954]
What I've tried:
- Multiple different ASM scripts for different purposes, CSV, HTLC, Simple p2shk like script to no avail
- I have successfully tested scripts that do NOT involve any signature verification, such as claiming with a hash/preimage.

Everything seems to be okay with the formation of the script and part of the creation of the redeem script. However, the underlying signature created does not seem to be valid according to the RegtestUtils and on Bitcoin proper. I'm not quite sure what I'm doing wrong and I've referenced the test integrations multiples times during the development process. Is there something special I'm missing related to the initialization of a private key? Or other edge case I am missing here? 

Running the following example code throws an error when broadcasting the redeem transaction to the regtest 

```typescript

import * as bitcoin from 'bitcoinjs-lib'
import { ECPairFactory } from 'ecpair'
import * as ecc from 'tiny-secp256k1'
import bip65 from 'bip65'
import bip68 from 'bip68'
import { RegtestUtils } from 'regtest-client'
import varuint from 'varuint-bitcoin'
import Crypto from 'crypto'

const APIPASS = process.env.APIPASS || 'satoshi'
const APIURL = process.env.APIURL || 'https://regtest.bitbank.cc/1'

export const regtestUtils = new RegtestUtils({ APIPASS, APIURL })

console.log(ECPairFactory)
bitcoin.initEccLib(ecc)
const ECPair = ECPairFactory(ecc)

// const bip65 = require('bip65');
interface KeyPair {
    publicKey: Buffer
  }
  function toOutputScript(address: string): Buffer {
    return bitcoin.address.toOutputScript(address, bitcoin.networks.regtest)
  }
  
  function idToHash(txid: string): Buffer {
    return Buffer.from(txid, 'hex').reverse()
  }

  function p2shScript(sender, receiver) {
    return bitcoin.script.compile([
      bitcoin.opcodes.OP_DUP,
      bitcoin.opcodes.OP_CHECKSIGVERIFY,
      bitcoin.opcodes.OP_HASH160,
      bitcoin.crypto.hash160(receiver.publicKey),
      bitcoin.opcodes.OP_EQUAL
   ]) 
}

void (async () => {
    const hashType = bitcoin.Transaction.SIGHASH_ALL
    // const keyPair = ECPair.makeRandom();
    //   const { address:address2 } = bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey });
    //   console.log(keyPair.toWIF(), address2)
      const aliceRegtest = ECPair.fromWIF(
    'cScfkGjbzzoeewVWmU2hYPUHeVGJRDdFt7WhmrVVGkxpmPP8BHWe',
    bitcoin.networks.regtest,
  )
  
  const bobRegtest = ECPair.fromWIF(
    'cMkopUXKWsEzAjfa1zApksGRwjVpJRB3831qM9W4gKZsLwjHXA9x',
    bitcoin.networks.regtest,
  )
  const height = await regtestUtils.height();
      // 5 blocks from now
   const lockTime = bip65.encode({ blocks: height + 5 });
   const redeemScript = p2shScript(aliceRegtest, bobRegtest)
   console.log(redeemScript)
 
   const p2sh = bitcoin.payments.p2sh({
     redeem: {
       output: redeemScript,
     },
     network: bitcoin.networks.regtest,
   })
   console.log(p2sh.address)


   const unspent = await regtestUtils.faucet(p2sh.address, 1e5)
  console.log('unpsnet', unspent)
  //At this point money has already been sent to the p2sh address
  const { address: returnAddress } = bitcoin.payments.p2pkh({
    pubkey: aliceRegtest.publicKey,
    network: bitcoin.networks.regtest,
  })
  console.log(returnAddress)
  const tx = new bitcoin.Transaction()
  tx.locktime = lockTime

//   tx.version = 2
  // Note: nSequence MUST be <= 0xfffffffe otherwise OP_CHECKLOCKTIMEVERIFY will fail.
  tx.addInput(idToHash(unspent.txId), 0, lockTime)
//   tx.addInput(idToHash(tXDB.txid), 0, bip65.encode({ blocks: height + 5 }))
  tx.addOutput(toOutputScript(regtestUtils.RANDOM_ADDRESS), 8e3)


  const signatureHash = tx.hashForSignature(0, p2sh.redeem.output, hashType)
//   console.log('signatureHash', signatureHash.toString('hex'), tx.getId())
  const redeemScriptInput = bitcoin.script.compile([
      bitcoin.script.signature.encode(bobRegtest.sign(signatureHash), bitcoin.Transaction.SIGHASH_ALL),
]) 
console.log(redeemScriptInput)
const redeemScriptSig = bitcoin.payments.p2sh({
    
    redeem: {
        input: redeemScriptInput,
        output: p2sh.redeem.output,
    },
})
tx.setInputScript(0, redeemScriptSig.input!)
console.log('ASM block', bitcoin.script.toASM(redeemScriptSig.input), 'ASM block2', bitcoin.script.toASM(redeemScript))
console.log(tx.toHex())
try {
      
    await regtestUtils.mine(12)
    await regtestUtils.broadcast(tx.toHex())
    await regtestUtils.mine(82)
    console.log(await regtestUtils.fetch(tx.getId()))
  // await regtestUtils.verify({
  //     txId: tx.getId(),
  //     address: regtestUtils.RANDOM_ADDRESS,
  //     vout: 0,
  //     value: 7e4,
  //   });
  await regtestUtils.mine(5)
} catch (ex) {
  console.log(ex)
}
})()

```

package.json deps

```json
    "bip32": "^4.0.0",
    "bip65": "^1.0.3",
    "bip68": "^1.0.4",
    "bitcoinjs-lib": "^6.1.3",
    "ecpair": "^2.1.0",
    "regtest-client": "^0.2.0",
    "tiny-secp256k1": "^2.2.3",
    "varuint-bitcoin": "^1.1.2",
```

Stacktrace:

```
Error: mandatory-script-verify-flag-failed (Public key is neither compressed or uncompressed)
    at C:\project\node_modules\dhttp\200.js:9:23
    at done (C:\project\node_modules\dhttp\index.js:13:19)
    at handle (C:\project\node_modules\dhttp\index.js:32:7)
    at C:\project\node_modules\dhttp\parsers.js:21:5
    at IncomingMessage.<anonymous> (C:\project\node_modules\dhttp\parsers.js:13:5)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21
```

**Comment by junderw** [comment]
You don't have any public key for the first CHECKSIG OP.

**Comment by junderw** [comment]
Your locking script:
`OP_DUP OP_CHECKSIGVERIFY OP_HASH160 <receiver_public_key> OP_EQUAL`

Your unlocking script:
`<receiver_signature>`

So your stack starts with a signature, then it dups, so 2 signatures. Then it runs OP_CHECKSIGVERIFY which expects a signature and a pubkey but it GOT 2 signatures...

A signature is not a valid pubkey, so it says "Public key is neither compressed or uncompressed" Because the signature is probably 73 bytes when it's looking for a 65 or 33 byte publickey.

**Comment by vaultec81** [comment]
Ahh I see. So I need to put the public key on the top of the stack then signature next to satisfy OP_CHECKSIGVERIFY? Is that roughly correct?
```typescript
const redeemScriptInput = bitcoin.script.compile([
      bobRegtest.publicKey,
      bitcoin.script.signature.encode(bobRegtest.sign(signatureHash), bitcoin.Transaction.SIGHASH_ALL),
]) 
```
```typescript
return bitcoin.script.compile([
    //   bitcoin.opcodes.OP_DUP,
      bitcoin.opcodes.OP_CHECKSIGVERIFY,
      bitcoin.opcodes.OP_HASH160,
      bitcoin.crypto.hash160(receiver.publicKey),
      bitcoin.opcodes.OP_EQUAL
   ]) 
   ```
   
   To be clear this is still triggering issues. Now throwing both 
```Error: non-mandatory-script-verify-flag (Witness requires empty scriptSig)```
   and
```Error: mandatory-script-verify-flag-failed (Non-canonical DER signature)```
Between runs

**Comment by junderw** [comment]
Please read this over: https://en.bitcoin.it/wiki/Script

Then think about what your "new" script does to the stack.

Come back with any questions.

**Comment by junderw** [comment]
I'm assuming by closing this you realized that you had the publicKey and signature order swapped.

The signature comes first, because it needs to be on the bottom of the stack.

**Comment by vaultec81** [comment]
@junderw Yep! That's roughly correct. Thank you for your help!

**Comment by Bunny801-cpu** [comment]
I'm facing the same problem. is there any solution for it? Whenever I try to make a transaction from my bitwallet mobile app, this error pops up. how can I fix it??
