### ISSUE TITLE
How to make a 1 to 1 transaction?

### ISSUE THREAD

**Issue by ruben2k1** [bitcoinjs/bitcoinjs-lib#1956]
```
const bitcoin = require('bitcoinjs-lib');
const { ECPairFactory } = require('ecpair');
const ecc = require('tiny-secp256k1');
const ECPair = ECPairFactory(ecc);
const axios = require('axios');
const BIP32Factory = require('bip32');
const bip32 = BIP32Factory.default(ecc);

const sendBTC = async () => {
    const network = bitcoin.networks.testnet;

    const clavePrivadaRemitente = ECPair.fromWIF('herethekeywifformat', network);
    const direccionRemitente = 'mwjQy4mHvLC4iv6VKJWR9LrQgTW3MqPhrH';
    const direccionDestinatario = 'n4VgpHyzZyJh3HZVCTXKogAM5hFh9Q8swM';

    let inputs = [];
    let inputsCount = 0;
    let totalAmountAvailable = 0;

    const psbt = new bitcoin.Psbt({ network });
    
    const res = await axios.get(`https://blockstream.info/testnet/api/address/${direccionRemitente}/utxo`);

    for (let i = 0; i < res.data.length; i++) {
        let input = {
            hash: res.data[i].txid,
            index: res.data[i].vout
        };

        totalAmountAvailable += res.data[i].value;

        inputsCount += 1;

        inputs.push(input);
    }

    psbt.addInputs(inputs);

    psbt.addOutput({
        address: direccionDestinatario,
        value: 8000,
    });

    psbt.signAllInputs(clavePrivadaRemitente);

    psbt.finalizeAllInputs();

    console.log(psbt.extractTransaction().toHex());
}

sendBTC();
```

Why it tells me that the inputs are not signed?

```
C:\xampp\htdocs\test_btc\node_modules\bitcoinjs-lib\src\psbt.js:597
      throw new Error('No inputs were signed');
            ^

Error: No inputs were signed
    at Psbt.signAllInputs (C:\xampp\htdocs\test_btc\node_modules\bitcoinjs-lib\src\psbt.js:597:13)
    at sendBTC (C:\xampp\htdocs\test_btc\1-1-Transaction.js:44:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

**Comment by junderw** [comment]
You need to add a nonWitnessUtxo for each input.

It is a Buffer of the parent transaction.
