### ISSUE TITLE
Error sending Litecoin transaction with blockcypher create transaction API

### ISSUE THREAD

**Issue by inspi-writer001** [bitcoinjs/bitcoinjs-lib#1994]
`error: 'Error validating generated transaction: Error running script for input 0 referencing bb6b200fd97d50b0a7541fe726f1329537d64f8530ebf41286cc534ebdd5e6ba at 0: Script was NOT verified successfully.'`

Here's the error I'm getting
I'm initially using trustwallet npm package  `@trustwallet/wallet-core@3.0.8` to generate the segwit address

I'm sure my private keys and wallet address are correct

Here's my code

```js
import bitcoin from "bitcoinjs-lib";
import axios from "axios";
import * as secp from "tiny-secp256k1";
import ecfacory, { ECPairFactory } from "ecpair";

const finallyTransferLitecoin = async (
  senderPrivateKey,
  senderAddress,
  receiverAddress,
  amountToTransfer
) => {
  let ECPair = ECPairFactory(secp);
  const keys = ECPair.fromPrivateKey(Buffer.from(senderPrivateKey, "hex"));
  const newTx = {
    inputs: [
      {
        addresses: [senderAddress]
      }
    ],
    outputs: [
      {
        addresses: [receiverAddress],
        value: toCustomLamport(amountToTransfer, 6)
      }
    ]
  };

  const utox = await axios.post(
    `https://api.blockcypher.com/v1/ltc/main/txs/new`,
    JSON.stringify(newTx)
  );

  log(utox.data);
  const response = utox.data;
  response.pubkeys = [];
  response.signatures = response.tosign.map((tosign, n) => {
    response.pubkeys.push(keys.publicKey.toString("hex"));

    return bitcoin.script.signature
      .encode(keys.sign(Buffer.from(tosign, "hex")), 0x01)
      .toString("hex")
      .slice(0, -2);
  });

  const tx = await axios.post(
    "https://api.blockcypher.com/v1/ltc/main/txs/send",
    JSON.stringify(response)
  );

  return tx.data;
};
```

Thanks for taking time to look into this

**Comment by inspi-writer001** [comment]
const LitecoinNet = {
  messagePrefix: "\x18Litecoin Signed Message:\n",
  bech32: "ltc",
  bip32: { public: 76067358, private: 76066276 },
  pubKeyHash: 48,
  scriptHash: 50,
  wif: 176
};
const network = LitecoinNet;

here's my network configurations

**Comment by junderw** [comment]
I'm sorry, I'm not familiar with the BlockCypher API, and since I can't see any of the data you're using, I have no way to reproduce the issue.

**Comment by junderw** [comment]
All I can say is your usage of signature encode is correct if you want DER encoded signatures with the sighash type byte taken off.

**Comment by inspi-writer001** [comment]
thank you,
are there alternatives to my approach?

and which would you specify?

**Comment by junderw** [comment]
Something like this:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/6e6b889ece668828d2fd188f00be2ad58f0be117/test/integration/transactions.spec.ts#L326-L358

**Comment by inspi-writer001** [comment]
thank you, I'll check it out right away

**Comment by inspi-writer001** [comment]
```
import { RegtestUtils } from 'regtest-client';

const APIPASS = process.env.APIPASS || 'satoshi';
const APIURL = process.env.APIURL || 'https://regtest.bitbank.cc/1';

export const regtestUtils = new RegtestUtils({ APIPASS, APIURL });
```

where do you recommend I get an api url from ?
Thank you for all the help

**Comment by inspi-writer001** [comment]
or rather, 
I'm getting this error


Error: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /1/b/best/height</pre>
</body>
</html>

    at /Users/mac/Documents/coinsafe-redo/node_modules/.pnpm/dhttp@3.0.3/node_modules/dhttp/200.js:9:23
    at done (/Users/mac/Documents/coinsafe-redo/node_modules/.pnpm/dhttp@3.0.3/node_modules/dhttp/index.js:13:19)
    at handle (/Users/mac/Documents/coinsafe-redo/node_modules/.pnpm/dhttp@3.0.3/node_modules/dhttp/index.js:32:7)
    at /Users/mac/Documents/coinsafe-redo/node_modules/.pnpm/dhttp@3.0.3/node_modules/dhttp/parsers.js:21:5
    at IncomingMessage.<anonymous> (/Users/mac/Documents/coinsafe-redo/node_modules/.pnpm/dhttp@3.0.3/node_modules/dhttp/parsers.js:13:5)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by inspi-writer001** [comment]
from trying this way

```

const getWitnessUtxo = (out) => {
  delete out.address;
  out.script = Buffer.from(out.script, "hex");
  return out;
};

const createPayment = (_type, myKeys, network = bitcoin.networks.bitcoin) => {
  network = network || regtest;
  const splitType = _type.split("-").reverse();
  const isMultisig = splitType[0].slice(0, 4) === "p2ms";
  const keys = myKeys || [];
  let m;
  if (isMultisig) {
    const match = splitType[0].match(/^p2ms\((\d+) of (\d+)\)$/);
    m = parseInt(match[1], 10);
    let n = parseInt(match[2], 10);
    if (keys.length > 0 && keys.length !== n) {
      throw new Error("Need n keys for multisig");
    }
    while (!myKeys && n > 1) {
      keys.push(ECPair.makeRandom({ network }));
      n--;
    }
  }

  if (!myKeys) keys.push(ECPair({ network }));

  let payment;
  splitType.forEach((type) => {
    if (type.slice(0, 4) === "p2ms") {
      payment = bitcoin.payments.p2ms({
        m,
        pubkeys: keys.map((key) => key.publicKey).sort((a, b) => a.compare(b)),
        network
      });
    } else if (["p2sh", "p2wsh"].indexOf(type) > -1) {
      payment = bitcoin.payments[type]({
        redeem: payment,
        network
      });
    } else {
      payment = bitcoin.payments[type]({
        pubkey: keys[0].publicKey,
        network
      });
    }
  });

  return {
    payment,
    keys
  };
};

const getInputData = async (amount, payment, isSegwit, redeemType) => {
  const unspent = await regtestUtils.faucetComplex(payment.output, amount);
  const utx = await regtestUtils.fetch(unspent.txId);
  // for non segwit inputs, you must pass the full transaction buffer
  const nonWitnessUtxo = Buffer.from(utx.txHex, "hex");
  // for segwit inputs, you only need the output script and value as an object.
  const witnessUtxo = getWitnessUtxo(utx.outs[unspent.vout]);
  const mixin = isSegwit ? { witnessUtxo } : { nonWitnessUtxo };
  const mixin2 = {};
  switch (redeemType) {
    case "p2sh":
      mixin2.redeemScript = payment.redeem.output;
      break;
    case "p2wsh":
      mixin2.witnessScript = payment.redeem.output;
      break;
    case "p2sh-p2wsh":
      mixin2.witnessScript = payment.redeem.redeem.output;
      mixin2.redeemScript = payment.redeem.output;
      break;
  }
  return {
    hash: unspent.txId,
    index: unspent.vout,
    ...mixin,
    ...mixin2
  };
};

const p2wpkh = createPayment("p2wpkh", [
  {
    privateKey: accountObject.privateKey,
    publicKey: Buffer.from(accountObject.publickKey)
  }
]);
log("========================== p2wpkh");
log(p2wpkh.payment.address);
log("========================== p2wpkh");
// log(regtestUtils.RANDOM_ADDRESS);

const btcTransferRecommend = async (
  senderPrivateKey,
  senderPublicKey,
  receiverAddress,
  amount
) => {
  const p2wpkh = createPayment("p2wpkh", [
    {
      privateKey: senderPrivateKey,
      publicKey: senderPublicKey
    }
  ]);
  const inputData = await getInputData(
    fromCustomLamport(amount, 6),
    p2wpkh.payment,
    true,
    "noredeem"
  );
  {
    const { hash, index, witnessUtxo } = inputData;
    assert.deepStrictEqual({ hash, index, witnessUtxo }, inputData);
  }

  const psbt = new bitcoin.Psbt({ network: regtest })
    .addInput(inputData)
    .addOutput({
      address: receiverAddress,
      value: fromCustomLamport(amount, 4)
    })
    .signInput(0, p2wpkh.keys[0]);

  assert.strictEqual(psbt.validateSignaturesOfInput(0, validator), true);
  psbt.finalizeAllInputs();

  const tx = psbt.extractTransaction();

  // build and broadcast to the Bitcoin RegTest network
  await regtestUtils.broadcast(tx.toHex());

  await regtestUtils.verify({
    txId: tx.getId(),
    address: receiverAddress,
    vout: 0,
    value: fromCustomLamport(amount, 4)
  });
};

```

**Comment by junderw** [comment]
> ```
> import { RegtestUtils } from 'regtest-client';
> 
> const APIPASS = process.env.APIPASS || 'satoshi';
> const APIURL = process.env.APIURL || 'https://regtest.bitbank.cc/1';
> 
> export const regtestUtils = new RegtestUtils({ APIPASS, APIURL });
> ```
> 
> where do you recommend I get an api url from ? Thank you for all the help

This is for bitcoin regtest. This is not for real usage.

Think of `getInputData` as a black box. You shouldn't be trying to re-create the behavior inside of it, you should be trying to get the input data it outputs on your own using some API like blockcypher or something.

**Comment by inspi-writer001** [comment]
ah, back to brainstorming then... thanks,
will let you know what I find out
