### ISSUE TITLE
Error: Expected property "pubkey" of type ?isPoint, got Uint8Array

### ISSUE THREAD

**Issue by charlieholy** [bitcoinjs/bitcoinjs-lib#2193]
that the version package list depends
(icecc) (icecc) [pechen@l2l3:9.1.2 bitcoin-27.0 (master)]# npm list bitcoinjs-lib
bitcoin-27.0@ /workspace/.bb/bitcoin-27.0
└── bitcoinjs-lib@6.1.7

(icecc) (icecc) [pechen@l2l3:9.1.2 bitcoin-27.0 (master)]# npm list tiny-secp256k1
bitcoin-27.0@ /workspace/.bb/bitcoin-27.0
└── tiny-secp256k1@2.2.3

(icecc) (icecc) [pechen@l2l3:9.1.2 bitcoin-27.0 (master)]# npm list ecpair
bitcoin-27.0@ /workspace/.bb/bitcoin-27.0
└── ecpair@3.0.0-rc.0

as for the demo i got this issue as title, so what happen?
/////////////////////////////////////////////////////
const bitcoin = require('bitcoinjs-lib');
const ecc = require('tiny-secp256k1');
const { ECPairFactory } = require('ecpair');

const ECPair = ECPairFactory(ecc);
const TESTNET = bitcoin.networks.testnet;

const keyPair = ECPair.fromWIF('KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn');
const publicKey = keyPair.publicKey;

const { address } = bitcoin.payments.p2pkh({ pubkey: publicKey });

console.log({ address });
///////////////////////////////////////////////////////

**Comment by charlieholy** [comment]
/workspace/.bb/bitcoin-27.0/node_modules/typeforce/index.js:117
        throw tfSubError(e, propertyName)
        ^
Error: Expected property "pubkey" of type ?isPoint, got Uint8Array
    at captureStackTrace (/workspace/.bb/bitcoin-27.0/node_modules/typeforce/errors.js:20:11)
    at tfSubError (/workspace/.bb/bitcoin-27.0/node_modules/typeforce/errors.js:99:3)
    at _object (/workspace/.bb/bitcoin-27.0/node_modules/typeforce/index.js:117:15)
    at typeforce (/workspace/.bb/bitcoin-27.0/node_modules/typeforce/index.js:233:9)
    at typeforce (/workspace/.bb/bitcoin-27.0/node_modules/typeforce/index.js:239:10)
    at Object.p2pkh (/workspace/.bb/bitcoin-27.0/node_modules/bitcoinjs-lib/src/payments/p2pkh.js:25:25)
    at Object.<anonymous> (/workspace/.bb/bitcoin-27.0/9.js:11:38)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32) {
  __label: undefined,
  __property: 'pubkey',
  __type: [Function: _maybe] { toJSON: [Function (anonymous)] },
  __value: Uint8Array(33) [
      2, 121, 190, 102, 126, 249, 220, 187,
    172,  85, 160,  98, 149, 206, 135,  11,
      7,   2, 155, 252, 219,  45, 206,  40,
    217,  89, 242, 129,  91,  22, 248,  23,
    152
  ],
  __valueTypeName: 'Uint8Array'
}

Node.js v20.12.2

**Comment by junderw** [comment]
ecpair v3 only works with bitcoinjs-lib v7

Please downgrade ecpair to v2 for now.
