### ISSUE TITLE
support for SIGHASH_SINGLE?  SIGHASH_ANYONECANPAY?

### ISSUE THREAD

**Issue by dthorpe** [bitcoinjs/bitcoinjs-lib#390]
Is anyone working on implementing support for SIGHASH_SINGLE and SIGHASH_ANYONECANPAY signature hashes in bitcoinjs?

**Comment by dcousens** [comment]
Happy to,  just haven't had time [as of yet].

**Comment by dthorpe** [comment]
what branch should I use for this?  main branch or 2.0 branch?

**Comment by dcousens** [comment]
The changes should be agnostic, and I'll likely back port them either way.
Just submit to the master branch if you decide to contribute.

**Comment by dthorpe** [comment]
Is the test suite supposed to work on Windows?

I've done "npm install ." from the bitcoinjs-lib project root, then "npm test", and I'm getting this error:

> bitcoinjs-lib@1.5.0 unit E:\src\bitcoinjs
> istanbul test mocha -- --reporter list test/*.js


E:\src\bitcoinjs\node_modules\.bin\mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (E:\src\bitcoinjs\node_modules\istanbul\lib\command\common\run-with
-cover.js:122:16)
    at Object.run (E:\src\bitcoinjs\node_modules\istanbul\lib\command\common\run
-with-cover.js:251:9)
    at TestCommand.Command.mix.run (E:\src\bitcoinjs\node_modules\istanbul\lib\c
ommand\test.js:27:22)
    at runCommand (E:\src\bitcoinjs\node_modules\istanbul\lib\cli.js:78:19)
    at runToCompletion (E:\src\bitcoinjs\node_modules\istanbul\lib\cli.js:82:5)

(The ^ is pointing to the @IF token)

**Comment by dcousens** [comment]
I don't know the solution solution yet, but a cursory look at http://stackoverflow.com/questions/27084392/code-coverage-for-mocha-in-windows-7 shows the same problem.

Looks like a path issue.

**Comment by dcousens** [comment]
Thanks @dthorpe,  I created https://github.com/bitcoinjs/bitcoinjs-lib/pull/400 in lieu of your PR.  Please review :)
