### ISSUE TITLE
TypeError: Cannot read property 'fromWIF' of undefined

### ISSUE THREAD

**Issue by bkawk** [bitcoinjs/bitcoinjs-lib#588]
Heres is my function taken from the test suite and just wrapped in a promise...
```
'use strict';
var bitcoin = require('bitcoinjs-lib');
//------------------------- NEW BITCOIN TRANSACTION -------------------------
exports.makeTransaction = function () {
    return new Promise(function(resolve, reject) {    
        var keyPair = bitcoin.ECPair.fromWIF('L1uyy5qTuGrVXrmrsvHWHgVzW9kKdrp27wBC7Vs6nZDTF2BRUVwy')
        var tx = new bitcoin.TransactionBuilder()
            tx.addInput('aa94ab02c182214f090e99a0d57021caffd0f195a81c24602b1028b130b63e31', 0)
            tx.addOutput('1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK', 15000)
            tx.sign(0, keyPair)
        var finalTX = tx.build().toHex();
        console.log(finalTX);
        if(finalTX){
            resolve(finalTX);
        }else{
            reject('Error');
        };
    }); //-- END PROMISE
};// END FUNCTION
```

Here I am calling it from my test using chai-as-promised....

```
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);
chai.should();
chai.config.includeStack = true; 
chai.config.showDiff = true;
chai.config.truncateThreshold = 0;

describe("Make a new transaction", function() {
    it("should return a promise", function(done) {
        var test = blockchain.makeTransaction();
        return test.should.be.fulfilled
        .notify(done);    
    });
}); 
```

Here is the exact error in the Terminal...

```
  1) Make a new bitcoin transaction should return a promise:
     AssertionError: expected promise to be fulfilled but it was rejected with [TypeError: Cannot read property 'fromWIF' of undefined]
      at assertIfNotNegated (node_modules/chai-as-promised/lib/chai-as-promised.js:84:23)
      at node_modules/chai-as-promised/lib/chai-as-promised.js:115:21
```

**Comment by dcousens** [comment]
What version of `bitcoinjs-lib` are you using?

**Comment by bkawk** [comment]
I'm running bitcoinjs-lib@1.5.8

**Comment by dcousens** [comment]
@bkawk `ECPair` is a feature from `2.0.0` :+1:

**Comment by bkawk** [comment]
Embarrassed and sorry, but thank you!

**Comment by lendetejas** [comment]
i have also same error i am using bitcoinjs-lib@6.1.5
