### ISSUE TITLE
Bitcoinjs-lib and pycoin multisig fails

### ISSUE THREAD

**Issue by shayanb** [bitcoinjs/bitcoinjs-lib#775]
I'm trying to get multisig running between pycoin and bitcoinjs-lib. 

This is the process: There's a request to pycoin to make unsigned_transaction, which is passed to bitcoinjs-lib to partially sign with key0, then it should be sent back to pycoin to fully sign with key1 and broadcast.

Now the first issue is that bitcoinjs-lib does not understand the tx_hex if it includes unspents so it has to return `unsigned_tx.as_hex(include_unspents=False)`, which would be this:
```
0100000001f37ca2227f044ea4de70d392e7923019905d29d5286517c1180ae0ed70b739cc0100000000ffffffff02c05d0000000000001976a9146efcf883b4b6f9997be9a0600f6c095fe2bd2d9288acc28300090000000017a9145629021f7668d4ec310ac5e99701a6d6cf95eb8f8700000000
```
it's bitcoin testnet transaction, so it could be decoded here: http://tbtc.blockr.io/tx/push

this is what bitcoinjs-lib returns as partially signed:
```
tx before fix: 0100000001f37ca2227f044ea4de70d392e7923019905d29d5286517c1180ae0ed70b739cc01000000fd140100473044022078e410e1f0e0e6abd39a6b80088ad1b123a4897994bebe17c3d0182842f19b5802204e1932b21e075dfae851b41437deba58a40bfcc2b162832e345acec3dc4d7025014cc95241048aa0d470b7a9328889c84ef0291ed30346986e22558e80c3ae06199391eae21308a00cdcfb34febc0ea9c80dfd16b01f26c7ec67593cb8ab474aca8fa1d7029d4104cf54956634c4d0bdaf00e6b1871c089b7a892d0fecc077f03b91e8d4d146861b0a4fdd237891a9819c878984d4b123f6fe92d9bbc05873a1bb4fe510145bf369410471843c33b2971e4944c73d4500abd6f61f7edf9ec919c408cbe12a6c9132d2cb8ebed8253322760d5ec6081165e0ab68900683de503f1544f03816d47fec699a53aeffffffff02c05d0000000000001976a9146efcf883b4b6f9997be9a0600f6c095fe2bd2d9288acc28300090000000017a9145629021f7668d4ec310ac5e99701a6d6cf95eb8f8700000000
```

Now when I try to sign them using pycoin, It fails with the following error:
```
script failed for unknown reason (/pycoin/tx/script/vm.py:243)
Traceback (most recent call last):
  File "/pycoin/tx/script/vm.py", line 211, in eval_script
    stack, signature_for_hash_type_f, expected_hash_type, script[begin_code_hash:], flags)
  File "/pycoin/tx/script/check_signature.py", line 233, in op_checkmultisig
    stack.pop()
  File "/pycoin/tx/script/vm.py", line 62, in pop
    raise ScriptError("pop from empty stack")
ScriptError: pop from empty stack
```

The same code works when the client is also pycoin.

I think the issue other than the unspent is the blank hash for the missing signatures. but can't figure out how either pycoin or bitcoinjs-lib makes those blank ones so I could implement it in the other.

This is a partially signed transaction with pycoin:
```
0100000001ce7ab62663a5bbd9e2682516ccf7ca3dfcfaaab37fde13274ddce3e6d91e45d201000000fd5d010047304402202fbd467bd2a12bf5c5116043f26a17f02d13fcf01da93adcf85d63f049116f5802207dabe5e297aa203c10720561fbae0ade0c3a4d62106b52c8a958afded32e419f01483045022100fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036414002207fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0014cc95241048aa0d470b7a9328889c84ef0291ed30346986e22558e80c3ae06199391eae21308a00cdcfb34febc0ea9c80dfd16b01f26c7ec67593cb8ab474aca8fa1d7029d4104cf54956634c4d0bdaf00e6b1871c089b7a892d0fecc077f03b91e8d4d146861b0a4fdd237891a9819c878984d4b123f6fe92d9bbc05873a1bb4fe510145bf369410471843c33b2971e4944c73d4500abd6f61f7edf9ec919c408cbe12a6c9132d2cb8ebed8253322760d5ec6081165e0ab68900683de503f1544f03816d47fec699a53aeffffffff02027608090000000017a9145629021f7668d4ec310ac5e99701a6d6cf95eb8f87c05d0000000000001976a9146efcf883b4b6f9997be9a0600f6c095fe2bd2d9288ac00000000
```

and this is partially signed transaction with bitcoinjs-lib
```
010000000135b7f879f44fe96ab5054506ea8621fa5b32d8210fbcba2779d0cf091e661c0601000000fd170100483045022100c20f92b000ac06420784379264b05b7bf58279981fb310dcd0b032f4e005d94d02205b6dd59c23e4eac33fa6c78dafc6eb679a17439e041d0e02ac709ecae703d8b10100004cc95241048aa0d470b7a9328889c84ef0291ed30346986e22558e80c3ae06199391eae21308a00cdcfb34febc0ea9c80dfd16b01f26c7ec67593cb8ab474aca8fa1d7029d4104cf54956634c4d0bdaf00e6b1871c089b7a892d0fecc077f03b91e8d4d146861b0a4fdd237891a9819c878984d4b123f6fe92d9bbc05873a1bb4fe510145bf369410471843c33b2971e4944c73d4500abd6f61f7edf9ec919c408cbe12a6c9132d2cb8ebed8253322760d5ec6081165e0ab68900683de503f1544f03816d47fec699a53aeffffffff02c05d0000000000001976a9146efcf883b4b6f9997be9a0600f6c095fe2bd2d9288ac3229f7050000000017a9145629021f7668d4ec310ac5e99701a6d6cf95eb8f8700000000
```

**Comment by dcousens** [comment]
What is the question?

**Comment by afk11** [comment]
Think he's trying to verify the full input signature once bitcoinjs has signed, but it only has one signature, so this can't be expected to work. (The error indicates that something was missing from the scriptSig)

To verify a partially signed transaction, you'll need to extract the signature from the scriptSig and do sighashing/ECDSA verification by hand.

**Comment by dcousens** [comment]
@shayanb did @afk11's answer help?
